kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
    - secrets
    providers:
    - kms:
        name: smartkey-test
        endpoint: unix:///opt/smartkey.socket
        cachesize: 100
        timeout: 3s
    - identity: {}
